layout_spectrum: 0.8959508454427123
typography_spectrum: 0.24250009725801647
color:
  brandStrength: 0.38944665947929025
  lightness: 0.5764222457073629
  saturation: 0.8879041112959385
  rhythmicContrast: 0.8815617873333395
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
name: Clark Carter
